# Generated by Django 3.2.19 on 2024-12-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0003_auto_20241218_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmate_taskdetails',
            name='acceptedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskmate_taskdetails',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
