# Generated by Django 3.2.19 on 2024-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0004_auto_20241218_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmate_taskdetails',
            name='status',
            field=models.CharField(default='Canceled', max_length=20),
        ),
    ]
