# Generated by Django 3.2.19 on 2024-12-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0005_alter_taskmate_taskdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmate_taskdetails',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
